firefox	Firefox	1	browser-firefox,browser-firefox-pywalfox	Arch official Firefox
chromium	Chromium	0	browser-chromium	Arch official Chromium
brave	Brave	0	browser-brave	Brave from AUR
zen-aur	Zen Browser AUR	0	browser-zen-aur	Zen from AUR
helium-aur	Helium Browser AUR	0	browser-helium-aur	Helium from AUR
