vscode	Visual Studio Code	1	dev-vscode	Visual Studio Code from AUR
neovim	Neovim	1	dev-neovim	Terminal editor
jetbrains-toolbox	JetBrains Toolbox	1	dev-jetbrains-toolbox	JetBrains Toolbox App
docker	Docker CE	1	dev-docker,dev-docker-post	Docker Engine
devtunnel	Microsoft Dev Tunnel CLI	1	dev-devtunnel	Microsoft Dev Tunnel CLI
lazygit	lazygit	1	dev-lazygit	Git terminal UI
lazydocker	lazydocker	1	dev-lazydocker	Docker terminal UI from Homebrew
