steam	Steam	0	gaming-steam	Steam from multilib
game-tools	GameMode Gamescope MangoHud	0	gaming-game-tools	Game performance tools
lutris	Lutris	0	gaming-lutris	Lutris package
heroic	Heroic Games Launcher	0	gaming-heroic	Heroic from AUR
