firefox	Firefox	1	browsers-firefox	Fast, privacy-focused web browser
chromium	Chromium	0	browsers-chromium	Open-source browser focused on speed, safety, and stability
chrome	Google Chrome	0	browsers-chrome	Fast and secure web browser by Google
brave	Brave	0	browsers-brave	Privacy-focused browser with built-in ad and tracker blocking
zen	Zen Browser	0	browsers-zen-copr	Privacy-focused browser with a customizable interface
helium	Helium Browser	0	browsers-helium-copr	Privacy-first browser with built-in ad and tracker blocking
