firefox	Firefox	1	browser-firefox	Fast, privacy-focused web browser
chromium	Chromium	0	browser-chromium	Open-source browser focused on speed, safety, and stability
chrome	Google Chrome	0	browser-chrome	Fast and secure web browser by Google
brave	Brave	0	browser-brave	Privacy-focused browser with built-in ad and tracker blocking
zen-copr	Zen Browser COPR	0	browser-zen-copr	Privacy-focused browser with a customizable interface
helium-copr	Helium Browser COPR	0	browser-helium-copr	Privacy-first browser with built-in ad and tracker blocking
