calculator	Calculator	1	desktop-calculator	Perform arithmetic, scientific, and financial calculations
characters	Characters	1	desktop-characters	Find and insert unusual characters
text-editor	Text Editor	1	desktop-text-editor	View and edit text files
disks	Disks	1	desktop-disks	Manage drives, disk images, partitions, and storage media
logs	Logs	1	desktop-logs	View detailed event logs for the system
disk-usage-analyzer	Disk Usage Analyzer	1	desktop-disk-usage-analyzer	Check folder sizes and available disk space
image-viewer	Image Viewer	1	desktop-image-viewer	View and edit images
document-viewer	Document Viewer	1	desktop-document-viewer	View PDF and other multi-page documents
video-player	Video Player	1	desktop-video-player	Play video files
audio-player	Audio Player	1	desktop-audio-player	Play audio files
camera	Camera	1	desktop-camera	Take pictures and videos
document-scanner	Document Scanner	1	desktop-document-scanner	Make digital copies of photos and documents
file-roller	File Roller	1	desktop-file-roller	Create, view, and extract archives
software	Software	1	desktop-software	Add, remove, and update graphical applications
system-monitor	System Monitor	1	desktop-system-monitor	View current processes and monitor system resources
boxes	Boxes	1	desktop-boxes	Create, view, and use virtual machines
connections	Connections	1	desktop-connections	View and use remote desktops
