vscode	Visual Studio Code	1	dev-vscode	Code editor with built-in debugging and source control
neovim	Neovim	1	dev-neovim	Extensible Vim-based text editor
jetbrains-toolbox	JetBrains Toolbox	1	dev-jetbrains-toolbox	App for installing, updating, and managing JetBrains IDEs
docker	Docker CE	1	dev-docker	Docker Engine, CLI, containerd, Buildx, and Compose for running containers
devtunnel	Microsoft Dev Tunnel CLI	1	dev-devtunnel	CLI for securely exposing local web services to the internet
lazygit	lazygit	1	dev-lazygit	Simple terminal interface for Git commands
lazydocker	lazydocker	1	dev-lazydocker	Simple terminal interface for Docker and Docker Compose
