codecs	Full multimedia codecs	1	media-codecs	Common audio, video, and Bluetooth aptX codecs plus detected AMD and Intel video acceleration
spotify	Spotify	1	media-spotify	Desktop client for streaming music and podcasts
