onlyoffice	OnlyOffice	1	office-onlyoffice	Desktop editors for documents, spreadsheets, presentations, forms, and PDFs
teams	Teams for Linux	1	office-teams	Unofficial Microsoft Teams desktop client with Linux integration
zoom	Zoom	1	office-zoom	App for video meetings, team chat, and collaboration
pinta	Pinta	1	office-pinta	Simple drawing and bitmap image editor
inkscape	Inkscape	1	office-inkscape	Vector graphics editor for illustrations, logos, diagrams, and more
