// Writes the GitHub plugin's emoji table (GitHubEmoji.js) from GitHub's
// emojis endpoint, which names each shortcode's image after its code
// points:
//
//   gh api emojis | node tests/support/github_emoji.js <GitHubEmoji.js>
//
// The image names leave out the zero-width joiners of a sequence and the
// emoji presentation selector, which are put back; GitHub's own images with
// no character (:octocat:, :shipit:) are left out, so they stay text.
"use strict";

const fs = require("fs");

const data = JSON.parse(fs.readFileSync(0, "utf8"));
const regional = c => c >= 0x1f1e6 && c <= 0x1f1ff;
// Whether a joiner goes between two code points: not before a skin tone, a
// keycap, a selector, or a tag, nor between the two letters of a flag.
const joins = (a, b) => !(b >= 0x1f3fb && b <= 0x1f3ff) && b !== 0x20e3 && b !== 0xfe0f && !(b >= 0xe0020 && b <= 0xe007f) && !(regional(a) && regional(b));
const out = {};
for (const [name, url] of Object.entries(data)) {
    const m = url.match(/\/unicode\/([0-9a-f-]+)\.png/);
    if (!m)
        continue;
    const cps = m[1].split("-").map(hex => parseInt(hex, 16));
    // Emoji presentation for characters that default to text.
    if (cps.length === 1 && cps[0] < 0x1f000)
        cps.push(0xfe0f);
    if (cps.length === 2 && cps[1] === 0x20e3)
        cps.splice(1, 0, 0xfe0f);
    const sequence = [cps[0]];
    for (let i = 1; i < cps.length; i++) {
        if (joins(cps[i - 1], cps[i]) && cps[i - 1] !== 0xfe0f || (cps[i - 1] === 0xfe0f && i > 1 && joins(cps[i - 2], cps[i])))
            sequence.push(0x200d);
        sequence.push(cps[i]);
    }
    out[name] = String.fromCodePoint(...sequence);
}
const names = Object.keys(out).sort();
let text = ".pragma library\n\n";
text += "// GitHub's emoji shortcodes (:tada:) and the characters github.com shows for\n";
text += "// them, from the REST API's emojis endpoint (gh api emojis), whose image\n";
text += "// names give the code points (the joiners of a sequence left out); its own\n";
text += "// images with no character (:octocat:, :shipit:) stay text. Generated by\n";
text += "// tests/support/github_emoji.js: run it again when GitHub adds new ones.\n";
text += "var EMOJI = {\n" + names.map(name => "    " + JSON.stringify(name) + ": " + JSON.stringify(out[name])).join(",\n") + "\n};\n";
fs.writeFileSync(process.argv[2], text);
