steam	Steam	0	gaming-steam-free,gaming-steam-nonfree	Steam via RPM Fusion
game-tools	GameMode Gamescope MangoHud	0	gaming-game-tools	Game performance tools
lutris	Lutris	0	gaming-lutris	Lutris package
heroic	Heroic Games Launcher	0	gaming-heroic	Heroic from Flathub
