onlyoffice	OnlyOffice	1	office-onlyoffice	OnlyOffice from Flathub
teams	Teams for Linux	1	office-teams	Teams for Linux from Flathub
zoom	Zoom	1	office-zoom	Zoom from Flathub
pinta	Pinta	1	office-pinta	Pinta from Flathub
inkscape	Inkscape	1	office-inkscape	Inkscape from Flathub
