id = "base-login-manager"
description = "DMS Greeter login manager for Fedora"

[base]
order = 60

[[install]]
backend = "dnf"
packages = ["policycoreutils-python-utils", "acl", "greetd"]

[[install]]
backend = "action"
sources = ["copr:avengemedia/danklinux"]
actions = ["dms-greeter"]
