id = "base-login-manager"
description = "Noctalia Greeter login manager for Fedora"

[base]
order = 60

[[install]]
backend = "dnf"
packages = ["policycoreutils-python-utils"]

[[install]]
backend = "action"
sources = ["copr:lionheartp/Hyprland"]
actions = ["noctalia-greeter"]
