"$schema" = "https://starship.rs/config-schema.json"
palette = "noctalia"

format = """
[](text)\
$os\
$username\
[](bg:blue fg:text)\
$directory\
[](fg:blue bg:yellow)\
$git_branch\
$git_status\
[](fg:yellow bg:sapphire)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$dotnet\
[](fg:sapphire bg:rosewater)\
$time\
[ ](fg:rosewater)\
$line_break$character"""

[os]
disabled = false
style = "bg:text fg:surface0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:text fg:surface0"
style_root = "bg:text fg:surface0"
format = '[ $user ]($style)'

[directory]
style = "fg:surface0 bg:blue"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = ".../"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:yellow"
format = '[[ $symbol $branch ](fg:surface0 bg:yellow)]($style)'

[git_status]
style = "bg:yellow"
format = '[[($all_status$ahead_behind )](fg:surface0 bg:yellow)]($style)'

[nodejs]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:surface0 bg:sapphire)]($style)'

[c]
symbol = " "
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:surface0 bg:sapphire)]($style)'

[rust]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:surface0 bg:sapphire)]($style)'

[golang]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:surface0 bg:sapphire)]($style)'

[php]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:surface0 bg:sapphire)]($style)'

[java]
symbol = " "
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:surface0 bg:sapphire)]($style)'

[kotlin]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:surface0 bg:sapphire)]($style)'

[haskell]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:surface0 bg:sapphire)]($style)'

[python]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:surface0 bg:sapphire)]($style)'

[dotnet]
symbol = "󰪮"
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:surface0 bg:sapphire)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:rosewater"
format = '[[  $time](fg:surface0 bg:rosewater)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:blue)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:blue)'
vimcmd_replace_one_symbol = '[](bold fg:green)'
vimcmd_replace_symbol = '[](bold fg:green)'
vimcmd_visual_symbol = '[](bold fg:yellow)'

# >>> NOCTALIA STARSHIP PALETTE >>>
[palettes.noctalia]
blue = "#89b4fa"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
cyan = "#94e2d5"
magenta = "#cba6f7"
white = "#cdd6f4"
black = "#11111b"
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
maroon = "#eba0ac"
peach = "#fab387"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
# <<< NOCTALIA STARSHIP PALETTE <<<
